# Generated by Django 3.2.6 on 2021-08-12 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocIdentidadModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.CharField(max_length=50, unique=True)),
                ('digitos', models.IntegerField()),
                ('estado', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento de Identidad',
                'verbose_name_plural': 'Documentos de Identidad',
                'db_table': 'docidentidad',
            },
        ),
        migrations.CreateModel(
            name='PacienteModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_index=True, max_length=255)),
                ('apellidos', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('nro_documento', models.CharField(db_index=True, max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.EmailField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('doc_ident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.docidentidadmodel')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'pacientes',
            },
        ),
    ]
