# Generated by Django 3.2.6 on 2021-08-12 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50, unique=True)),
                ('estado', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='SubCategoriaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategoria', models.CharField(max_length=50)),
                ('estado', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudio.categoriamodel')),
            ],
            options={
                'verbose_name': 'Sub Cateoria',
                'verbose_name_plural': 'Sub Categorias',
                'db_table': 'subcategorias',
            },
        ),
        migrations.CreateModel(
            name='EstudioModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estudio', models.CharField(db_index=True, max_length=255, unique=True)),
                ('estado', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudio.categoriamodel')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudio.subcategoriamodel')),
            ],
            options={
                'verbose_name': 'Estudio',
                'verbose_name_plural': 'Estudios',
                'db_table': 'estudios',
            },
        ),
    ]
