# Generated by Django 3.2.6 on 2021-08-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registromodel',
            options={'verbose_name': 'Atencion', 'verbose_name_plural': 'Atenciones'},
        ),
        migrations.AlterField(
            model_name='registromodel',
            name='url_file',
            field=models.FileField(blank=True, default='-', null=True, upload_to='file/resultados'),
        ),
        migrations.AlterModelTable(
            name='registromodel',
            table='atenciones',
        ),
    ]
